"""US-02 T1: tabla cliente

Revision ID: 06b4cea4f487
Revises: af5526385936
Create Date: 2026-10-07 11:11:31.175241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b4cea4f487'
down_revision = 'af5526385936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=60), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_cliente_id_usuario_usuario')),
    sa.PrimaryKeyConstraint('id_cliente', name=op.f('pk_cliente')),
    sa.UniqueConstraint('cedula', name=op.f('uq_cliente_cedula')),
    sa.UniqueConstraint('id_usuario', name=op.f('uq_cliente_id_usuario'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
